### ISSUE TITLE
Async hook wrappers?

### ISSUE THREAD

**Issue by takluyver** [pypa/pyproject-hooks#1]
The wrappers to call PEP 517 hooks in a subprocess are completely synchronous: they write files, start a subprocess, wait for that to exit, and read output files before returning. For many applications, I expect that is what we want.

This issue is to collect info on whether there is a need for machinery to call hooks *asynchronously*, and if so whether this package should provide the machinery or some lower-level pieces to build it out of.

If you want to call PEP 517 hooks asynchronously, please comment here, but start building the machinery you need as part of your own project. We probably won't add async parts to this package before we have a couple of potential users to figure out what code it's useful to share.

**Comment by pradyunsg** [comment]
Given the lack of expressed interest over the last 6 years, I'll go ahead and close this out.
