### ISSUE TITLE
Create a compatibility `pep517` wrapper package

### ISSUE THREAD

**Issue by KOLANICH** [pypa/pyproject-hooks#160]
The package was renamed, but too a lot of packages depend on `pep517`.

So it is proposed

1. create a `pep517` branch in this repo
2. within this branch create a `pep517` package depending on `pyproject_hooks`. The package should contain nothing more than aliases to the renamed API and deprecation warnings instructing people to migrate. The ReadMe file should also contain migration instructions.
3. publish it on `pypi`.

**Comment by takluyver** [comment]
I think I'm happy enough with the current situation - we've documented that pep517 is deprecated, and made a [`legacy` branch](https://github.com/pypa/pyproject-hooks/tree/legacy) to represent it, but we haven't added warnings. If projects are already happy with `pep517` does, it's not a problem for them to carry on using it, and if/when they're not happy, it should be easy for them to switch over.

**Comment by KOLANICH** [comment]
>If projects are already happy with pep517 does, it's not a problem for them to carry on using it, and if/when they're not happy, it should be easy for them to switch over.

It causes bloat for 2 copies of the same thing and violates the DRY principle.

**Comment by takluyver** [comment]
Sorry, it just doesn't seem worth getting excited about.
