### ISSUE TITLE
Add renamed/deprecated notice to pypi.org/project/pep517

### ISSUE THREAD

**Issue by hroncok** [pypa/pyproject-hooks#178]
Could you please add a new release of pep517 that links to pyproject-hooks (and build) quite visibly in the long description? Currently, when I go to https://pypi.org/project/pep517/, nothing warns me I should not use that package.

Thanks.

**Comment by takluyver** [comment]
I've just uploaded 0.13.1, propagating the warning from the README to PyPI.

**Comment by hroncok** [comment]
Thanks
