### ISSUE TITLE
Release version 1.1?

### ISSUE THREAD

**Issue by Secrus** [pypa/pyproject-hooks#183]
Hello!
Any chance for a v1.1 release? v1.0 is over a year old by now and we could use the type annotations. I am happy to help if possible.
Thanks!

**Comment by Secrus** [comment]
@takluyver @pfmoore ping for attention.

**Comment by pradyunsg** [comment]
Hah, it looks like I can cut a release. Lemme see what the state of this project is and whether this would be a quick thing for me to do.

**Comment by jonglezb** [comment]
Agreed, type annotations would be nice to have for downstream projects!

**Comment by takluyver** [comment]
OK, the release is done now, after a brief hiccup with the CI.
