### ISSUE TITLE
RFE: Provide better control of how arguments are passed to hooks

### ISSUE THREAD

**Issue by radekholy24** [pypa/pyproject-hooks#185]
Hello, I'd like to ask you to provide better control of which arguments are passed to the hooks positionally and which are passed as keyword arguments (and which parameters are provided and which are not).

IIUIC, at this moment all arguments are passed positionally and it is rather an implementation detail.

My aim is not to change PEP 517 or change current PEP 517 implementations as in https://github.com/pypa/pyproject-hooks/issues/115.

Rather, the other way around, I aim to build a correct implementation of a PEP 517 build backend. To be sure that the implementation is correct I want to build a comprehensive (integration) test suite that makes sure that the specification is met in all aspects. One of the requirements is also:

> The hooks may be called with positional or keyword arguments, so backends implementing them should be careful to make sure that their signatures match both the order and the names of the arguments above.

Most of the new build backend's functionality can be tested through your library. However, the aspect mentioned above cannot.

I am aware of the fact that my use case is rather rare (even though it should not) and the feature is of limited usefulness in other cases. However, since at this moment, I do not see any way to fully test the backend other than copying most of this library while including this little tweak, I feel the urge to request this feature first before reinventing the wheel.

I do not request any specific implementation. But I would like to ask for such a future-proof implementation that is rather explicit than implicit. Not just because it is required by the Zen of Python but especially because this feature is going to be used only in special cases and these cases might be easily forgotten and thus this feature may easily disappear without notice. E.g. if the support for this feature was that the library just passed the same (positional and keyword) arguments as was passed to the library, a future maintainer might not notice that this is not just an implementation detail and might change it. Thus I imagine support for custom hook callers for example.

**Comment by takluyver** [comment]
Hmmm... I'm not totally convinced. I think it's admirable to try to ensure that your backend works with both positional and keyword arguments, but it seems like a fair bit of extra complexity in this package which is only useful for the specific case of testing backends. And if it ever becomes a problem in practice, the standard might just be updated to say that one convention is preferred. :shrug: 

Could you use [`inspect.signature(hook).bind(...)`](https://docs.python.org/3/library/inspect.html#inspect.Signature.bind) to test your backend? I.e. bind the same hook with positional args & with keyword args, and verify that the resulting bindings are the same?

**Comment by radekholy24** [comment]
Wow, I wasn't aware of [`inspect.signature(hook).bind(...)`](https://docs.python.org/3/library/inspect.html#inspect.Signature.bind). Well, sounds like an interesting suggestion for a unit test but unfortunately, I don't see a way to use it in an *integration* test. Although, I admit that my insistence on testing this aspect through an integration test is questionable.

Nevermind. I just wanted to make sure that I have exhausted all options before reinventing the wheel. I perfectly understand your reasoning. Feel free to close the issue.
